# -*- coding: utf-8 -*-
"""SnapcommerceCodeByteAssessment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gB0Pmt7KbTRA2V6zjW9EM3HeCI7dO3tD

### Name: Michael Solodko
### Snapcommerce Codebyte Assessment
"""

#loading pandas and numpy module
import pandas as pd
import numpy as np

#loading data into df
df = pd.DataFrame({'To_From': ['WAterLoo_NEWYork', 'Montreal_TORONTO', 'CALgary_Ottawa','Ottawa_VANcouvER', 'london_MONTreal'],
                   'FlightCodes': [20015.0, np.nan, 20035.0, np.nan, 20055.0],
                   'DelayTimes': [[21, 40], [], [60, 22, 87], [78, 66], [12, 33]],
                   'Airline Code': ['Air Canada (!)', '<Air France> (12)', '(Porter Airways. )','12. Air France', '""".\\.Lufthansa.\\."""']})

#printing data table
df.head()

"""### 1.FlightCodes column"""

#Getting initial value in FlightCodes column
init_val = df.FlightCodes.loc[[0]].values[0]

#Traversing through FlightCodes column, and adding new codes to null values while incrementing by 10
new_codes = [init_val + 10*i for i in range(len(df.FlightCodes))]

#Adding new_codes back to FlightCodes column
df.FlightCodes = new_codes

#Converting FlightCodes from type float to type int
df.FlightCodes = df.FlightCodes.astype(int)

#printing DataFrame
df.head()

"""### 2. To_From column"""

#Splitting To_From column at '_' into a new DataFrame called df_temp
df_temp=df.To_From.str.split(pat='_',expand=True)

#Naming the two split columns 'From' and 'To'
df_temp.columns =['From', 'To']

#Converting names into correct capital case
df_temp.From = df_temp.From.str.capitalize()
df_temp.To = df_temp.To.str.capitalize()

# Concatenating the original df and df_temp
df=pd.concat((df_temp, df), axis=1)

#Deleteing 'To_From' column
del df['To_From']

#Printing df
df.head()

"""### 3. Airline Code column"""

#Removing all punctutation from 'Airline Code' except Spaces and letters
df['Airline Code']=df['Airline Code'].str.replace('[^a-zA-Z ]', '',regex=True)

#printing df
df.head()